/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { SignalsClient } from './SignalsClient';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { _NestedCategoryModel } from './models/_NestedCategoryModel';
export type { _NestedDepartmentModel } from './models/_NestedDepartmentModel';
export { _NestedLocationModel } from './models/_NestedLocationModel';
export { _NestedMySignalLocation } from './models/_NestedMySignalLocation';
export type { _NestedMySignalStatus } from './models/_NestedMySignalStatus';
export type { _NestedNoteModel } from './models/_NestedNoteModel';
export type { _NestedPriorityModel } from './models/_NestedPriorityModel';
export type { _NestedPrivateCategoryDepartment } from './models/_NestedPrivateCategoryDepartment';
export type { _NestedPublicDepartment } from './models/_NestedPublicDepartment';
export type { _NestedPublicStatusModel } from './models/_NestedPublicStatusModel';
export type { _NestedReporterModel } from './models/_NestedReporterModel';
export type { _NestedStatusModel } from './models/_NestedStatusModel';
export type { _NestedTypeModel } from './models/_NestedTypeModel';
export type { _SignalsPerCategoryCount } from './models/_SignalsPerCategoryCount';
export type { _SimpleCategory } from './models/_SimpleCategory';
export type { AbridgedChildSignal } from './models/AbridgedChildSignal';
export type { ActiveTermsFacet } from './models/ActiveTermsFacet';
export type { Area } from './models/Area';
export { AreaGeo } from './models/AreaGeo';
export type { AreaType } from './models/AreaType';
export { BlankEnum } from './models/BlankEnum';
export type { CancelSignalReporter } from './models/CancelSignalReporter';
export type { Category } from './models/Category';
export type { CategoryDepartment } from './models/CategoryDepartment';
export type { CategoryHAL } from './models/CategoryHAL';
export type { EmailPreview } from './models/EmailPreview';
export type { EmailPreviewPost } from './models/EmailPreviewPost';
export type { EmailVerification } from './models/EmailVerification';
export type { Expression } from './models/Expression';
export type { Feedback } from './models/Feedback';
export { FieldTypeEnum } from './models/FieldTypeEnum';
export type { GenericError } from './models/GenericError';
export { GisFeatureEnum } from './models/GisFeatureEnum';
export { HandlingEnum } from './models/HandlingEnum';
export type { Highlight } from './models/Highlight';
export type { HistoryLogHal } from './models/HistoryLogHal';
export type { Meta } from './models/Meta';
export type { MySignalsLoggedInReporter } from './models/MySignalsLoggedInReporter';
export type { MySignalsToken } from './models/MySignalsToken';
export type { NullEnum } from './models/NullEnum';
export type { PaginatedAbridgedChildSignalList } from './models/PaginatedAbridgedChildSignalList';
export type { PaginatedAreaList } from './models/PaginatedAreaList';
export type { PaginatedCategoryList } from './models/PaginatedCategoryList';
export type { PaginatedExpressionList } from './models/PaginatedExpressionList';
export type { PaginatedPermissionList } from './models/PaginatedPermissionList';
export type { PaginatedPrivateCategoryList } from './models/PaginatedPrivateCategoryList';
export type { PaginatedPrivateDepartmentSerializerListList } from './models/PaginatedPrivateDepartmentSerializerListList';
export type { PaginatedPrivateSignalAttachmentList } from './models/PaginatedPrivateSignalAttachmentList';
export type { PaginatedPrivateSignalSerializerListList } from './models/PaginatedPrivateSignalSerializerListList';
export type { PaginatedPublicQuestionSerializerDetailList } from './models/PaginatedPublicQuestionSerializerDetailList';
export type { PaginatedRoleList } from './models/PaginatedRoleList';
export type { PaginatedSignalContextReporterList } from './models/PaginatedSignalContextReporterList';
export type { PaginatedSignalIdListList } from './models/PaginatedSignalIdListList';
export type { PaginatedSignalListList } from './models/PaginatedSignalListList';
export type { PaginatedSignalReporterList } from './models/PaginatedSignalReporterList';
export type { PaginatedSourceList } from './models/PaginatedSourceList';
export type { PaginatedStandardAnswerList } from './models/PaginatedStandardAnswerList';
export type { PaginatedStatusMessageList } from './models/PaginatedStatusMessageList';
export type { PaginatedStoredSignalFilterList } from './models/PaginatedStoredSignalFilterList';
export type { PaginatedUserListHALList } from './models/PaginatedUserListHALList';
export type { PaginatedUserNameListList } from './models/PaginatedUserNameListList';
export type { ParentCategoryHAL } from './models/ParentCategoryHAL';
export type { PatchedExpression } from './models/PatchedExpression';
export type { PatchedFeedback } from './models/PatchedFeedback';
export type { PatchedPrivateCategory } from './models/PatchedPrivateCategory';
export type { PatchedPrivateCategoryIcon } from './models/PatchedPrivateCategoryIcon';
export type { PatchedPrivateDepartmentSerializerList } from './models/PatchedPrivateDepartmentSerializerList';
export type { PatchedPrivateSignalAttachmentUpdate } from './models/PatchedPrivateSignalAttachmentUpdate';
export type { PatchedPrivateSignalSerializerList } from './models/PatchedPrivateSignalSerializerList';
export type { PatchedRole } from './models/PatchedRole';
export type { PatchedStatusMessage } from './models/PatchedStatusMessage';
export type { PatchedStoredSignalFilter } from './models/PatchedStoredSignalFilter';
export type { PatchedUserDetailHAL } from './models/PatchedUserDetailHAL';
export type { Permission } from './models/Permission';
export { PriorityEnum } from './models/PriorityEnum';
export type { PrivateCategory } from './models/PrivateCategory';
export type { PrivateCategoryHistoryHal } from './models/PrivateCategoryHistoryHal';
export type { PrivateCategoryIcon } from './models/PrivateCategoryIcon';
export type { PrivateCategorySLA } from './models/PrivateCategorySLA';
export type { PrivateDepartmentSerializerDetail } from './models/PrivateDepartmentSerializerDetail';
export type { PrivateDepartmentSerializerList } from './models/PrivateDepartmentSerializerList';
export type { PrivateSignalAttachment } from './models/PrivateSignalAttachment';
export type { PrivateSignalAttachmentUpdate } from './models/PrivateSignalAttachmentUpdate';
export type { PrivateSignalSerializerDetail } from './models/PrivateSignalSerializerDetail';
export type { PrivateSignalSerializerList } from './models/PrivateSignalSerializerList';
export type { PrivateUserHistoryHal } from './models/PrivateUserHistoryHal';
export type { ProfileDetail } from './models/ProfileDetail';
export type { ProfileList } from './models/ProfileList';
export type { PublicQuestionSerializerDetail } from './models/PublicQuestionSerializerDetail';
export type { PublicSignalAttachment } from './models/PublicSignalAttachment';
export type { PublicSignalCreate } from './models/PublicSignalCreate';
export type { PublicSignalSerializerDetail } from './models/PublicSignalSerializerDetail';
export type { ReportSignalsPerCategory } from './models/ReportSignalsPerCategory';
export type { Role } from './models/Role';
export type { RoutingExpression } from './models/RoutingExpression';
export type { SignalContext } from './models/SignalContext';
export { SignalContextReporter } from './models/SignalContextReporter';
export type { SignalDetail } from './models/SignalDetail';
export type { SignalIdList } from './models/SignalIdList';
export type { SignalList } from './models/SignalList';
export type { SignalReporter } from './models/SignalReporter';
export type { Source } from './models/Source';
export { StadsdeelEnum } from './models/StadsdeelEnum';
export type { StandardAnswer } from './models/StandardAnswer';
export { State187Enum } from './models/State187Enum';
export type { StateStatusMessageTemplate } from './models/StateStatusMessageTemplate';
export { StateStatusMessageTemplateStateEnum } from './models/StateStatusMessageTemplateStateEnum';
export type { StateTermsFacet } from './models/StateTermsFacet';
export { StatusEnum } from './models/StatusEnum';
export type { StatusMessage } from './models/StatusMessage';
export type { StatusMessageCategoryPosition } from './models/StatusMessageCategoryPosition';
export type { StatusMessageFacet } from './models/StatusMessageFacet';
export type { StatusMessageList } from './models/StatusMessageList';
export type { StatusMessageSearchResult } from './models/StatusMessageSearchResult';
export type { StoredSignalFilter } from './models/StoredSignalFilter';
export { TargetApiEnum } from './models/TargetApiEnum';
export type { TemporaryCategoryHAL } from './models/TemporaryCategoryHAL';
export type { TemporaryParentCategoryHAL } from './models/TemporaryParentCategoryHAL';
export type { TmpCategory } from './models/TmpCategory';
export type { UseCalendarDaysEnum } from './models/UseCalendarDaysEnum';
export type { UserDetailHAL } from './models/UserDetailHAL';
export type { UserListHAL } from './models/UserListHAL';
export type { UserNameList } from './models/UserNameList';
export type { ValidationError } from './models/ValidationError';

export { V1Service } from './services/V1Service';
