name: Lint and build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: "Lint"
        run: |
          npm run lint

      - name: "Build"
        run: |
          npm run build
